In [1]:
import pandas as pd
df = pd.read_csv("stats.csv")
df

        Name  Salary Country
0        Dan   40000     USA
1  Elizabeth   32000  Brazil
2        Jon   45000   Italy
3      Maria   54000     USA
4       Mark   72000     USA
5       Bill   62000  Brazil
6       Jess   92000   Italy
7      Julia   55000     USA
8       Jeff   35000   Italy
9        Ben   48000  Brazil

In [3]:
#Measure of Central Tendancy
#Mean Salary
mean1=df["Salary"].mean()
mean1

53500.0

In [4]:
#Sum of Salaries
sum1 = df["Salary"].sum()
sum1

535000

In [5]:
#Max Salary
max1 = df["Salary"].max()
max1

92000

In [6]:
#Min Salary
min1 = df["Salary"].min()
min1

32000

In [7]:
#Total Count( of row)
count1 = df["Salary"].count()
count1

10

In [8]:
#Median of Salary
median1 = df["Salary"].median()
median1

51000.0

In [9]:
#Mode of Salary
mode1 = df["Salary"].mode()
mode1

0    32000
1    35000
2    40000
3    45000
4    48000
5    54000
6    55000
7    62000
8    72000
9    92000
Name: Salary, dtype: int64

In [10]:
country_wise_sum = df.groupby(["Country"])["Salary"].sum()
country_wise_sum

Country
Brazil    142000
Italy     172000
USA       221000
Name: Salary, dtype: int64

In [11]:
country_wise_count = df.groupby(["Country"]).count()
country_wise_count

         Name  Salary
Country
Brazil      3       3
Italy       3       3
USA         4       4

In [12]:
#Measure of Variability
var1 = df["Salary"].var()
var1

332055555.5555556

In [13]:
std1 = df["Salary"].std()
std1

18222.391598128816

In [14]:
#Measure of Symmetry
skew1 = df.skew(axis=0,skipna=True)
skew1

C:\Users\admin\AppData\Local\Temp\ipykernel_4444\4267036063.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  skew1 = df.skew(axis=0,skipna=True)

Salary    1.021551
dtype: float64

In [16]:
#The skewness is positive so x will have right side tail.
df.describe()

             Salary
count     10.000000
mean   53500.000000
std    18222.391598
min    32000.000000
25%    41250.000000
50%    51000.000000
75%    60250.000000
max    92000.000000